### ISSUE TITLE
Encoder Sensor not working

### ISSUE THREAD

**Issue by erkeller** [FYSETC/FYSETC-ERCF-Kit#1]
I have swopped the cables as indicated in the Known Issues section, but the light on the Encoder sensor stays on and does not blink when the filament moves through the selector. It does not register any movement of the filament at all. After the first Home, the sensor shows disabled on the Mainsail Dashboard. 

I copied the ercf_hardware.cfg as supplied here. Please assist.

**Comment by Awesome4all** [comment]
What did you do to fix it?
